# Generated by Django 4.0.5 on 2022-12-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('price', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('price1', models.CharField(max_length=120)),
            ],
        ),
    ]
