# Generated by Django 4.0.5 on 2022-12-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price1', models.CharField(max_length=150)),
                ('price2', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
    ]
