# Generated by Django 4.0.5 on 2022-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='sotilganlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('customer', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=150)),
                ('naqd', models.CharField(max_length=150)),
                ('plastik', models.CharField(max_length=150)),
                ('nasiya', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('price1', models.CharField(max_length=150)),
            ],
        ),
    ]
